#コンテキストパス設定
server.servlet.context-path=/shop
#ポート番号
server.port=7777
#キャッシュ無効
spring.thymeleaf.cache=false


# 5章 設定ファイル5-1

#JSなどでCookie情報を読み取り禁止
server.servlet.session.cookie.http-only=true
#セッション情報をCookieに格納する
server.servlet.session.tracking-modes=cookie

# 5章 設定ファイル5-2
#セッションタイムアウトを20秒に設定
server.servlet.session.timeout=0

# 6章 設定ファイル6-2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#21cの場合のURL
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1

#11gの場合のURL
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

#データベースユーザー名、パスワード
spring.datasource.username=spring_user
spring.datasource.password=systemsss

# 6章 設定ファイル6-3

#SQLのWHERE句などに設定する値を出力

# SQL文をコンソール出力する
logging.level.org.hibernate.SQL=debug

# 【SpringBoot3.x～】バインドパラメータ（値）を出力する
logging.level.org.hibernate.orm.jdbc.bind=trace

#出力するSQLを整形する
spring.jpa.properties.hibernate.format_sql=true

#SpringBoot2の設定
#logging.level.org.hibernate.type.descriptor.sql=trace

#整形されていないSQLを見たい場合はこちらを使う
#spring.jpa.show-sql=true
